# Generated by Django 4.2.29 on 2026-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('pg', 'PG'), ('tiffin', 'Tiffin'), ('plumber', 'Plumber')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('per_visit', 'Per Visit')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('rating', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
