# Generated by Django 4.2.29 on 2026-09-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('pg', 'PG / Hostel'), ('tiffin', 'Tiffin Service'), ('maid', 'Maid Service'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('internet', 'Internet Provider')], max_length=50),
        ),
    ]
