# Generated by Django 4.2.29 on 2026-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requirement',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
