# Generated by Django 4.2.29 on 2026-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('english', models.CharField(blank=True, max_length=200)),
                ('hindi', models.CharField(blank=True, max_length=200)),
                ('tamil', models.CharField(blank=True, max_length=200)),
                ('kannada', models.CharField(blank=True, max_length=200)),
                ('bengali', models.CharField(blank=True, max_length=200)),
                ('marathi', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
